apiVersion: v1
kind: Service
metadata:
  name: project2-backend-service
  namespace: project2
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP

