apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1-app
  template:
    metadata:
      labels:
        app: project1-app
    spec:
      containers:
        - name: test-pod
          image: wiings09/test-image:v1 

