apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namePrefix: paytm-
nameSuffix: -dev

namespace: dev

replicas:
  - name: deployment
    count: 2

labels:
  - pairs:
      env: dev
    includeSelectors: true
    includeTemplates: true

patches:
  - target:
        group: apps
        version: v1
        kind: Deployment
        name: deployment
    patch: |-
        - op: replace
          path: /spec/template/spec/containers/0/resources/requests/cpu
          value: "50m"
        - op: replace
          path: /spec/template/spec/containers/0/resources/requests/memory
          value: "130Mi"
        - op: replace
          path: /spec/template/spec/containers/0/ports/0/containerPort
          value: 9090
  - target: 
      group: ""
      version: v1
      kind: Service
      name: service
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 9090
      - op: replace
        path: /spec/ports/0/targetPort
        value: 9090