apiVersion: v1
kind: Service
metadata:
  name: project-10-backend-svc
  namespace: project-10
spec:
  type: ClusterIP
  selector:
    app: project-10-backend
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 6450