apiVersion: v1
kind: Service
metadata:
  name: project-10-frontend-svc
  namespace: project-10
spec:
  type: ClusterIP
  selector:
    app: project-10-frontend
  ports:
    - protocol: TCP
      port: 6869
      targetPort: 80