apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-11-deploy
  labels:
    app: deploy-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy-demo
  template:
    metadata:
      labels:
        app: deploy-demo
    spec:
      containers:
      - name: canary-demo
        image: wafiqhossain/demo-app:v1.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP