apiVersion: v1
kind: Service
metadata:
  name: project-11-svc
  labels:
    app: canary-demo
spec:
  type: ClusterIP
  selector:
    app: canary-demo
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP