apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-app
          image: wafiqhossain/demo-app:v1.0
          ports:
            - containerPort: 3000
