apiVersion: v1                  # API version for core Kubernetes resources
kind: LimitRange               # This resource sets default resource limits in a namespace

metadata:
  name: dev-limitRange
  namespace: dev           

spec:
  limits:
    - type: Container          # Applies these rules to each container (not Pod level)

      default:                 # MAX limit 
        cpu: "500m"            # Max CPU a container can use (500 millicores = 0.5 CPU)
        memory: "256Mi"        # Max memory a container can use (256 MB)

      defaultRequest:          # MIN guaranteed resources
        cpu: "100m"            # Minimum CPU guaranteed (0.1 CPU)
        memory: "128Mi"        # Minimum memory guaranteed (128 MB)